import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[cursor]
style = "Block"
vi_mode_style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.glyph_offset]
y = 0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
y = 0

[scrolling]
history = 1000
multiplier = 3

[window.padding]
x = 24
y = 24
